<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 06.11.18
 * Time: 16:09
 */

?>

<h1>Login</h1>

<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Please sign in</h2>
            <?php if ($content['isLoginError']): ?>
                <p class="small">Login or pass incorrect</p>
            <?php endif; ?>
            <?= $this->formLabel($content['form']->get('login')); ?>
            <?= $this->formElement($content['form']->get('login')); ?>
            <?= $this->formLabel($content['form']->get('password')); ?>
            <?= $this->formElement($content['form']->get('password')); ?>
            <div class="checkbox">
                <label>
                    <?= $this->formElement($content['form']->get('remember_me')); ?> Remember me
                </label>
            </div>
            <?= $this->formElement($content['form']->get('redirect_url')); ?>
            <?= $this->formElement($content['form']->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
    </div>
</div>
