<h1>User</h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($content['form']); ?>

        <div class="form-group">
            <?= $this->formLabel($content['form']->get('login')); ?>
            <?= $this->formElement($content['form']->get('login')); ?>
            <?= $this->formElementErrors($content['form']->get('login')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($content['form']->get('password')); ?>
            <?= $this->formElement($content['form']->get('password')); ?>
            <?= $this->formElementErrors($content['form']->get('password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($content['form']->get('confirm_password')); ?>
            <?= $this->formElement($content['form']->get('confirm_password')); ?>
            <?= $this->formElementErrors($content['form']->get('confirm_password')); ?>
        </div>


        <?= $this->formElement($content['form']->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>